### PR TITLE
Allow .dataprinter to be a symlink

### PR DESCRIPTION
**Pull request by Flimm**
This fixes this bug:

https://rt.cpan.org/Ticket/Display.html?id=88566

### CODE REVIEW

**Comment by bessarabov** [comment]
Some time ago there was a discussoin about this issue and @garu explained why he don't want this file to be a symlink: https://github.com/garu/Data-Printer/pull/34#issuecomment-13681461

**Comment by Flimm** [comment]
Ah. When I saw the open bug report, I assumed that that it was a valid bug report and not a "wontfix".

**Comment by derobert** [comment]
@garu Read through your comment (back in 2013) on the pull request, and I'd like to point out if an attacker can already create arbitrary files in `$HOME`, you're already very hosed. Trivial examples include `.bashrc`, a bunch of stuff under `ssh/*`, `.gitconfig`, `~/bin'… All of those, by the way, allow symlinks.

Environment variables, OTOH, often *are* under someone else's control. For example, how CGI passes HTTP headers—in environment variables. Forgetting that has been the source of a few CVEs lately (e.g., the 14 or so collectively called httpoxy); it made Shellshock worse,…). Thankfully your variable doesn't start with `HTTP_`.

(This is also breaking my dotfile management setup. And using the envvar instead isn't really a solution—for one thing, consistently setting an env var w/o root access is harder, and second having each program need custom handling doesn't scale well).

**Comment by garu** [comment]
Hey everyone! Took us a while but the new version of Data::Printer (on github master and released to CPAN as 0.99_X - soon to be 1.0) changed the format of .dataprinter files to be much safer and simpler without running `eval`. Also, @derobert's analysis was quite convincing - so symlinks are a go!

I have not merged this PR because of conflicts but your names are credited in the docs!

(also, please note that the `.dataprinter` format has changed and needs to be adjusted. Let me know if you bump into any issues)

Thanks again!

**Comment by Flimm** [comment]
That is nice of you to name me in the credits. Cheers!

**Pull request closed without merging**
